version: "3.8"

services:
  betapi:
    build: ./
    # env_file:
    #   - .env
    # command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn bet_api:api --host 0.0.0.0 --port 8000 --reload"]
    # environment:
    #   - APP_MESSAGE=Hello debugger
    volumes:
      - ./:/app
    ports:
      - "5678:5678"
      - "8000:8000"
    restart: unless-stopped